# Generated by Django 4.2.16 on 2024-10-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversationroom_conversation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationroom',
            name='title',
            field=models.CharField(default='Default Room', max_length=255),
        ),
    ]
