# Generated by Django 4.2.16 on 2024-10-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversationroom_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationroom',
            name='role',
        ),
    ]
