# Generated by Django 4.2.16 on 2024-10-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_attachedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationroom',
            name='attached_file',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='conversation_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='chatbot.conversationroom'),
        ),
    ]
